# General text 
#############################################
description: Pisaster is a consultancy providing quantitative support that turns ecological data into actionable insights for conservation organizations.
title: Pisaster
footer_overview_text: "Pisaster is a consultancy providing quantitative support that turns ecological data into actionable insights for conservation organizations."


# Logos
#############################################
logo: pisaster-logo.svg
logoAlt: Pisaster
favicon: pisaster-favicon.png
faviconAlt: Pisaster


# Github
#############################################
git_repo: https://github.com/pisaster/website


# General email addresses
#############################################
hello_email: team@pisaster.org
info_email: membership@pisaster.org


# Social media and communication platforms
#############################################
youtube: https://www.youtube.com/pisaster
linkedin: https://www.linkedin.com/company/pisaster/
bluesky: https://bsky.app/profile/pisaster.com


# Technical parameters
#############################################

# To include "search" option from 404 page
include404search: true 